config/routes.rb
Rails.application.routes.draw do
  root             'base#index'
  get  'about'     => 'base#about'
  get  'login'     => 'sessions#new'
  post 'login'     => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'     =>  'users#new'

  resources :users do
    resources :contacts
    resources :custom_fields
  end

end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  # Relations
  belongs_to :user
  has_many :custom_field_info, dependent: :destroy

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :style, presence: true
  validates_inclusion_of :style, in: %w[text text_area combobox], allow_nil: false

end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  before_action :session_right_user, only: [:edit, :update, :index, :show]

  def index
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.all
    @page_title = 'All Custom Fields'
  end

  def show
  end

  def new
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.new
    @form_params = { head_title: "Add a custom field", submit_message: "Add",
                     form_path: user_custom_fields_path, form_method: :post }
    @page_title = 'New Custom Field'

    render 'layouts/_customfields_form'
  end

  def edit
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.find(params[:id])
    @form_params = { head_title: "Edit custom field", submit_message: "Edit",
                     form_path: user_custom_field_path, form_method: :patch }
    @page_title = 'Edit Custom Field'

    render 'layouts/_customfields_form'
  end

  def create
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.build(custom_field_params)
    if @custom_field.save
      redirect_to user_custom_fields_path(@user)
    else
      @form_params = { head_title: "Add a custom field", submit_message: "Add",
                       form_path: user_custom_fields_path, form_method: :post }
      @page_title = 'Add Custom Field'
      render 'layouts/_customfields_form'
    end
  end

  def update
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.find(params[:id])

    if @custom_field.update_attributes(custom_field_params)
      redirect_to user_custom_fields_path(@user)
    else
      @form_params = { head_title: "Edit custom field", submit_message: "Edit",
                       form_path: user_custom_field_path, form_method: :patch }
      @page_title = 'Edit Custom Field'
      render 'layouts/_customfields_form'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @custom_field = @user.custom_field.find(params[:id])
    @custom_field.destroy

    redirect_to user_custom_fields_path(@user)
  end

  private
    def custom_field_params
      params.require(:custom_field).permit(:name, :style)
    end
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
end

app/views/custom_fields/index.html.erb
<div class="jumbotron">

  <h1>Your Custom Fields</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table">
        <thead>
          <th>Name</th>
          <th>Type</th>
        </thead>
        <tbody>
          <% @custom_field.each do |c| %>
          <tr>
            <td> <%= c.name %> </td>
            <td> <%= c.style %> </td>
            <td> <%= link_to "Edit", edit_user_custom_field_path(session_logged_user.id, c.id) %> </td>
            <td> <%= link_to "Delete", user_custom_field_path(session_logged_user.id, c.id), method: "delete", data: { confirm: "Are you sure?" } %> </td>
          <tr>
          <% end %>
        </tbody>
      </table>
        <p><%= link_to "Add new custom field", new_user_custom_field_path(session_logged_user), class: "btn btn-lg btn-success" %></p>
    </div>
  </div>
</div>