config/routes.rb
Rails.application.routes.draw do
  root             'base#index'
  get  'about'     => 'base#about'
  get  'login'     => 'sessions#new'
  post 'login'     => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'     =>  'users#new'

  resources :users do
    resources :contacts
    resources :custom_fields
  end

end

app/views/layouts/_contacts_form.html.erb
<div class="center jumbotron">
  <h1><%= @form_params[:head_title] %></h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <%= form_for @contact, url: @form_params[:form_path], method: @form_params[:form_method] do |form| %>
        <%= render 'shared/error_messages' %>

        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>

        <%= form.label :lastname %>
        <%= form.text_field :lastname, class: 'form-control' %>

        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>

          <%# Prototype of how custom fields info should be edited%>
          <%#= form.fields_for :custom_field_info do |cfi| %>
              <%#= cfi.label :data %>
              <%#= cfi.text_field :data, class: 'form-control' %>
          <%# end %>

        <p><%= form.submit @form_params[:submit_message], class: "btn btn-lg btn-success" %></p>
      <% end %>
      </div>
    </div>
</div>

app/views/layouts/_customfields_form.html.erb
<div class="center jumbotron">
  <h1><%= @form_params[:head_title] %></h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <%= form_for @custom_field, url: @form_params[:form_path], method: @form_params[:form_method] do |form| %>
        <%= render 'shared/error_messages' %>

        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
        
        <p class="custom_field"><%= form.radio_button(:style, 'text') %>
        <%= form.label(:style_text, "Text") %></p>
        <p class="custom_field"><%= form.radio_button(:style, 'text_area') %>
        <%= form.label(:style_text_area, "Text Area") %></p>
        <p class="custom_field"><%= form.radio_button(:style, 'combo_box') %>
        <%= form.label(:style_combo_box, "Combo Box") %></p>

        <p><%= form.submit @form_params[:submit_message], class: "btn btn-lg btn-success" %></p>
      <% end %>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <p>Built with ♥</p>
</footer>

app/views/layouts/_header.html.erb
<header class="masthead">
  <div class="container">
    <nav>
      <div class="navbar-header">
        <% if session_is_logged? %>
          <%= link_to "RD Contacts", user_contacts_path(session_logged_user) , class: "navbar-brand" %>
        <% else %>
          <%= link_to "RD Contacts", root_path, class: "navbar-brand" %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if session_is_logged? %>
          <li> <%= link_to "Contacts", user_contacts_path(session_logged_user)%> </li>
          <li> <%= link_to "Custom Fields", user_custom_fields_path(session_logged_user)%> </li>
          <li> <%= link_to "Profile", edit_user_path(session_logged_user)%> </li>
          <li><%= link_to "About", about_path %></li>
          <li> <%= link_to "Logout", logout_path, method: "delete" %> </li>
        <% else %>
          <li> <%= link_to "Login", login_path %> </li>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "About", about_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_users_form.html.erb
<div class="center jumbotron">
  <h1><%= @form_params[:head_title] %></h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <%= form_for @user, url: @form_params[:form_path], method: @form_params[:form_method] do |form| %>
        <%= render 'shared/error_messages' %>

        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>

        <%= form.label :lastname %>
        <%= form.text_field :lastname, class: 'form-control' %>

        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>

        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>

        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: 'form-control' %>

        <p><%= form.submit @form_params[:submit_message], class: "btn btn-lg btn-success" %></p>
      <% end %>

      <% if @form_params[:form_method] == :patch %>
        <p><%= link_to "Delete me", user_path(session_logged_user), method: "delete", data: { confirm: "Are you sure? All your data will be lost!" } %></p>
      <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RD Contacts | <%= @page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>